# Generated by Django 3.0.5 on 2020-04-20 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioAreaName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioTypeName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioTitle', models.CharField(max_length=256)),
                ('scenarioDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenarioDescription', models.TextField()),
                ('scenarioInitial', models.TextField(blank=True, null=True)),
                ('scenarioFinal', models.TextField(blank=True, null=True)),
                ('scenarioArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ScenarioArea')),
                ('scenarioAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenarioType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ScenarioType')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=256)),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scenario')},
                'index_together': {('user', 'scenario')},
            },
        ),
    ]
