# Generated by Django 3.0.5 on 2020-04-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentScenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Scenario'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=256)),
                ('testCondition', models.TextField(blank=True, null=True)),
                ('testSteps', models.TextField(blank=True, null=True)),
                ('testExpectedResult', models.TextField(blank=True, null=True)),
                ('testScenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scenario')),
            ],
        ),
    ]
